version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.12.2"
      MEMORY: "4G"
      Level_TYPE: "BIOMESOP"
    volumes:
      - ./data:/data

    tty: true
    stdin_open: true
    restart: unless-stopped


