version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.12.2"
      MEMORY: "4G"
      LEVEL_TYPE: "BIOMESOP"
      ONLINE_MODE: "FALSE"
      MOTD: "A Docker power Minecraft server, inspired by StarGate"
      MAX_PLAYERS: "20"
      WORLD_NAME: "SG1:S0E1"
      RCON_PASSWORD: "password"



    volumes:
      - ./data:/data

    tty: true
    stdin_open: true
    restart: unless-stopped


