name: Docker Compose Actions Workflow
on: push
jobs:
  mvp-check:
    runs-on: ubuntu-latest
    steps:
      - name: Do we need to Build?
        run: |
          git diff --exit-code test docker-compose.yaml
  build:
    needs: mvp-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker images
        run: docker-compose build

      - name: Build the stack
        run: docker-compose up -d

      - name: Test
        run: docker ps -a --format "table {{.Names}}" | grep "ipk-minegate_mc_1"

