name: Docker Compose Actions Workflow
on: push
paths:
- 'docker-compose.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker images
        run: docker-compose build

      - name: Build the stack
        run: docker-compose up -d

      - name: Test
        run: docker ps -a --format "table {{.Names}}" | grep "ipk-minegate_mc_1"

